
CREATE TABLE public.ROLES (
                ID_ROL VARCHAR NOT NULL,
                NOMBRE_ROL VARCHAR NOT NULL,
                CONSTRAINT roles_pk PRIMARY KEY (ID_ROL)
);


CREATE TABLE public.PROJECT (
                ID_PROJECT VARCHAR NOT NULL,
                CONSTRAINT project_pk PRIMARY KEY (ID_PROJECT)
);


CREATE TABLE public.TEAM (
                ID_TEAM NUMERIC NOT NULL,
                TEAM_NAME VARCHAR NOT NULL,
                CONSTRAINT team_pk PRIMARY KEY (ID_TEAM)
);


CREATE TABLE public.USERS  (
                USER_NAME VARCHAR NOT NULL,
                NOMBRE VARCHAR NOT NULL,
                PASS VARCHAR NOT NULL,
                CONSTRAINT users__pk PRIMARY KEY (USER_NAME)
);


CREATE TABLE public.ROL_IN_POROJECT (
                USER_NAME VARCHAR NOT NULL,
                ID_ROL VARCHAR NOT NULL,
                ID_PROJECT VARCHAR NOT NULL,
                ID_TEAM NUMERIC NOT NULL,
                CONSTRAINT rol_in_poroject_pk PRIMARY KEY (USER_NAME, ID_ROL, ID_PROJECT, ID_TEAM)
);


CREATE TABLE public.USERS_STORIES (
                ID_US VARCHAR NOT NULL,
                 NOMBRE VARCHAR NOT NULL,
                PRIORIDAD VARCHAR NOT NULL,
                RIESGO VARCHAR NOT NULL,
                DESCRIPCION VARCHAR(300) NOT NULL,
                USER_NAME VARCHAR NOT NULL,
                ID_ROL VARCHAR NOT NULL,
                ID_PROJECT VARCHAR NOT NULL,
                ID_TEAM NUMERIC NOT NULL,
                CONSTRAINT user_stories_pk PRIMARY KEY (ID_US)
);


CREATE TABLE public.PRODUCT_BACKLOG (
                ID_PB VARCHAR NOT NULL,
                ID_US VARCHAR NOT NULL,
                CONSTRAINT product_backlog_pk PRIMARY KEY (ID_PB, ID_US)
);


CREATE TABLE public.SPRINT (
                ID_SPRINT VARCHAR NOT NULL,
                ESTADO VARCHAR NOT NULL,
                TIEMPO_SPRINT NUMERIC NOT NULL,
                ID_PB VARCHAR NOT NULL,
                ID_US VARCHAR NOT NULL,
                CONSTRAINT sprint_pk PRIMARY KEY (ID_SPRINT)
);


CREATE TABLE public.TAREAS (
                ID_TAREAS VARCHAR NOT NULL,
                ESTADO VARCHAR NOT NULL,
                DESCRIPCION VARCHAR NOT NULL,
                ID_SPRINT VARCHAR NOT NULL,
                CONSTRAINT tareas_pk PRIMARY KEY (ID_TAREAS)
);


ALTER TABLE public.ROL_IN_POROJECT ADD CONSTRAINT roles_rol_in_poroject_fk
FOREIGN KEY (ID_ROL)
REFERENCES public.ROLES (ID_ROL)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ROL_IN_POROJECT ADD CONSTRAINT project_rol_in_poroject_fk
FOREIGN KEY (ID_PROJECT)
REFERENCES public.project (ID_PROJECT)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ROL_IN_POROJECT ADD CONSTRAINT team_rol_in_poroject_fk
FOREIGN KEY (ID_TEAM)
REFERENCES public.team (ID_TEAM)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ROL_IN_POROJECT ADD CONSTRAINT users__rol_in_poroject_fk
FOREIGN KEY (USER_NAME)
REFERENCES public.users  (USER_NAME)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.user_stories ADD CONSTRAINT rol_in_poroject_user_stories_fk
FOREIGN KEY (USER_NAME, ID_ROL, ID_PROJECT, ID_TEAM)
REFERENCES public.ROL_IN_POROJECT (USER_NAME, ID_ROL, ID_PROJECT, ID_TEAM)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PRODUCT_BACKLOG ADD CONSTRAINT user_stories_product_backlog_fk
FOREIGN KEY (ID_US)
REFERENCES public.user_stories (ID_US)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.SPRINT ADD CONSTRAINT product_backlog_sprint_fk
FOREIGN KEY (ID_PB, ID_US)
REFERENCES public.PRODUCT_BACKLOG (ID_PB, ID_US)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.Tareas ADD CONSTRAINT sprint_tareas_fk
FOREIGN KEY (ID_SPRINT)
REFERENCES public.SPRINT (ID_SPRINT)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
